name: Build ClLinux

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x cl.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debootstrap \
            xorriso \
            squashfs-tools \
            grub-pc-bin \
            grub-efi-amd64-bin \
            build-essential

      - name: Run build script
        run: |
          export TERM=xterm-256color
          sudo ./cl.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
